### ISSUE TITLE
UX: Bridgy to Twitter makes some unfortunate default photo choices

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/bridgy-publish#10] opened 2016-07-28 18:34 UTC
Surely I should have put in a featured image, but otherwise it's grabbing multiple low res photos on the same page (in widgets, footer, or from gravatar author block) which don't correspond well with the content : 
![bridgy publish](https://cloud.githubusercontent.com/assets/5882943/17224684/cd9bde56-54b6-11e6-8a49-870bf0946620.PNG)

Maybe default to none if not a featured image or appearing within the_content()?

**Comment by dshanske** [comment] 2016-07-28 19:04
I am working on more logic on the WordPress side, but the issue is that Microformats is a theme, not a plugin issue usually.

**Comment by dshanske** [comment] 2016-07-28 19:07
The only solution I can think of is to write something that can be turned off and which has a good explanation of what on and off are.

**Comment by chrisaldrich** [comment] 2016-07-28 21:31
<a href="https://github.com/dshanske/bridgy-publish/issues/10" class="u-in-reply-to"></a>Sounds like a reasonable solution. I'd imagine that in most cases (to be safe) that if there's not a featured image, then posts to twitter would generally be just the text update as that's how most people typically use twitter. 

Is it looking for photo related microformats with regard to identifying/pulling photos? I actually thought it was interesting/relatively nice that it automatically pulled the three photos and laid them out that way, but in that case I'd have done higher res photos for better clarity. The "indieweb mini-logo" is a really small icon way down in the footer of my page and I was most shocked that it popped up on the post.

I typically have been using SNAP for POSSE, but as I've been watching your work recently, I felt compelled to test out Bridgy Publish to give you some feedback about UX/UI as well as bang on things for bugs in general.

**Comment by dshanske** [comment] 2016-08-01 15:40
Can you cross-post this issue to Bridgy itself?

**Comment by snarfed** [comment] 2016-08-01 20:22
replied in https://github.com/snarfed/bridgy/issues/691#issuecomment-236695656.

**Comment by dshanske** [comment] 2017-01-14 18:15
May revisit this as a markup issue elsewhere, but closing it as a plugin issue.

**Closed as completed by dshanske** 2017-01-14 18:15 UTC
