### ISSUE TITLE
surface errors from bridgy to user

### ISSUE THREAD

**Issue by snarfed** [dshanske/bridgy-publish#21] opened 2017-01-25 19:59 UTC
based on this ongoing conversation with cdevroe: https://chat.indieweb.org/2017-01-25/1485372011628000

... it sounds like errors from bridgy, ie non -2xx responses and their bodies, are currently dropped on the floor and nor shown to the user. it'd be nice to show them at some point. :P

specifically the error here from attempting to publish  :

`Couldn't find link to brid.gy/publish/twitter`

log: https://brid.gy/log?start_time=1485371674&key=aglzfmJyaWQtZ3lyOgsSDVB1Ymxpc2hlZFBhZ2UiE2h0dHA6Ly9jZGV2cm9lLmNvbS8MCxIHUHVibGlzaBiAgICAgICACgw

docs: https://brid.gy/about#webmentions

(btw, the plugin should probably add this link itself if necessary, right?)

i hate to say it, but the easiest way to surface errors is probably to switch from async cron to synchronous, so you have the response and can show it to the user right then.

thanks again for all your work on this plugin!

**Comment by snarfed** [comment] 2017-01-25 20:29
looks like the same thing happened to @cdevroe on facebook:

https://brid.gy/facebook/10158195666450370#publishes

https://brid.gy/log?start_time=1485371678&key=aglzfmJyaWQtZ3lyOgsSDVB1Ymxpc2hlZFBhZ2UiE2h0dHA6Ly9jZGV2cm9lLmNvbS8MCxIHUHVibGlzaBiAgICAgOSRCgw

**Comment by dshanske** [comment] 2017-01-25 20:54
I just switched to async, partly because of an odd other issue. But I think I can take a page from SNAP on how they handle it. In the last update, the error is returned, but not acted on.

**Comment by dshanske** [comment] 2017-01-25 21:01
I think I have to figure out how the link is not going when the Webmention is. I never could reproduce in testing

**Comment by dshanske** [comment] 2017-01-25 21:01
I think I have to figure out how the link is not going when the Webmention is. I never could reproduce in testing

**Comment by dshanske** [comment] 2017-01-25 21:02
And @snarfed, the plugin is merely a UI for the wonderful service you built and maintain.

**Comment by snarfed** [comment] 2017-01-25 21:25
thanks for the kind words!

i have a fair amount of experience with async vs sync, and honestly, the code and UX will both be *much* simpler and better if you go back to sync. it will cost a second or two in latency per publish, but i'm pretty sure it'll be worth it in this case. just my 2¢.

**Comment by dshanske** [comment] 2017-01-25 22:38
Actually I did it partially because the setting of the manual fill in for mf2_syndication kept conflicting with the automatic one from the Webmention. Other ways to solve it.

**Comment by dshanske** [comment] 2017-02-11 05:27
Deploying a fix for this shortly.

**Comment by snarfed** [comment] 2018-01-09 19:10
more complaints about this: https://chat.indieweb.org/2018-01-09#t1515524954448400

**Comment by dshanske** [comment] 2018-02-25 04:26
I think I have fixed this in the latest version.

**Closed as completed by dshanske** 2018-02-25 04:26 UTC
